name: Actions workflow

on:
  schedule:
  - cron: '*/6 * * * *'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Log pre build disc-space
        run: df

      - name: Step 2 - checkout the master branch
        uses: actions/checkout@v2

      - name: Step 3 - setup jdk 1.8 
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Step 4 - Build your jakarta web app with maven
        run: echo mvn -B package --file pom.xml

      - name: Step 5 - build the  native android app
        run: |
          echo Here is the ANDROID_SDK_ROOT
          echo $ANDROID_SDK_ROOT

      - name: Step 6 - Run your selenium tests
        run: |
          echo the SELENIUM_JAR_PATH
          echo $SELENIUM_JAR_PATH

      - name: Log build tools versions
        run: |
          git --version
          mvn --version
          ant -version
          gradle --version

      - name: Step 8 - Log the post-build disc space
        run: df  
